# Your presentation title
title: Soutenance Final

# The Reveal theme
reveal_theme: beige.css

# The Reveal transition
reveal_transition: fast

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options: 

# Additional reveal.js dependencies
reveal_dependencies: 

# Reveal.js subdirectory
reveal_path: reveal.js/


markdown: redcarpet
highlighter: pygments
markdown_ext: ignoreme

exclude:
 - .idea
 - .circleci
 - .gitignore
 - .gitmodule
 - Dockerfile
 - README.md
